### ISSUE TITLE
assert(self.profile_info)

### ISSUE THREAD

**Issue by johnsoong** [cornell-zhang/dnn-quant-ocs#1]
Traceback (most recent call last):
  File "compress_classifier.py", line 765, in <module>
    main()
  File "compress_classifier.py", line 298, in main
    return evaluate_model(model, criterion, train_loader, test_loader, pylogger, args)
  File "compress_classifier.py", line 701, in evaluate_model
    top1, _, _ = test(test_loader, model, criterion, loggers, args=args)
  File "compress_classifier.py", line 483, in test
    return _validate(test_loader, model, criterion, loggers, args)
  File "compress_classifier.py", line 515, in _validate
    output = model(inputs)
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torchvision/models/resnet.py", line 139, in forward
    x = self.conv1(x)
  File "/home/songyan3/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/songyan3/experiments/dnn-quant-ocs/distiller/quantization/ocs.py", line 169, in forward
    assert(self.profile_info)

Excuse me, have you met such question in running example.sh? it seems that self.profile_info has not been assigned =A=

**Comment by JohnnMason** [comment]
Traceback (most recent call last):
  File "compress_classifier.py", line 763, in <module>
    main()
  File "compress_classifier.py", line 298, in main
    return evaluate_model(model, criterion, train_loader, test_loader, pylogger, args)
  File "compress_classifier.py", line 699, in evaluate_model
    top1, _, _ = test(test_loader, model, criterion, loggers, args=args)
  File "compress_classifier.py", line 483, in test
    return _validate(test_loader, model, criterion, loggers, args)
  File "compress_classifier.py", line 515, in _validate
    output = model(inputs)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torchvision/models/resnet.py", line 196, in forward
    x = self.conv1(x)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/notebook/code/personal/80296970/dnn-quant-ocs/distiller/quantization/ocs.py", line 168, in forward
    assert(self.profile_info)
AssertionErro

I also meet the same problem during test, and I haven't modified anything

**Comment by JohnnMason** [comment]
I also meet the same problem during test, and I haven't modified anything

**Comment by amishacorns** [comment]
I will have to look into this more, but could you check if the issue is still there when run with a single GPU (if you are using multiple)?

**Comment by JohnnMason** [comment]
> I will have to look into this more, but could you check if the issue is still there when run with a single GPU (if you are using multiple)?

Really appreciate! It works! I did use multiple GPUs and it works when I set  arg --gpus 0. 
Then I can study your method further. Thank you very much!
